// FontAwesome icon names
export const glyphMap = [
  "adjust",
  "anchor",
  "archive",
  "area-chart",
  "arrows",
  "arrows-h",
  "arrows-v",
  "asterisk",
  "at",
  "automobile",
  "balance-scale",
  "ban",
  "bank",
  "bar-chart",
  "bar-chart-o",
  "barcode",
  "bars",
  "battery-0",
  "battery-1",
  "battery-2",
  "battery-3",
  "battery-4",
  "battery-empty",
  "battery-full",
  "battery-half",
  "battery-quarter",
  "battery-three-quarters",
  "bed",
  "beer",
  "bell",
  "bell-o",
  "bell-slash",
  "bell-slash-o",
  "bicycle",
  "binoculars",
  "birthday-cake",
  "bluetooth",
  "bluetooth-b",
  "bolt",
  "bomb",
  "book",
  "bookmark",
  "bookmark-o",
  "briefcase",
  "bug",
  "building",
  "building-o",
  "bullhorn",
  "bullseye",
  "bus",
  "cab",
  "calculator",
  "calendar",
  "calendar-check-o",
  "calendar-minus-o",
  "calendar-o",
  "calendar-plus-o",
  "calendar-times-o",
  "camera",
  "camera-retro",
  "car",
  "caret-square-o-down",
  "caret-square-o-left",
  "caret-square-o-right",
  "caret-square-o-up",
  "cart-arrow-down",
  "cart-plus",
  "cc",
  "certificate",
  "check",
  "check-circle",
  "check-circle-o",
  "check-square",
  "check-square-o",
  "child",
  "circle",
  "circle-o",
  "circle-o-notch",
  "circle-thin",
  "clock-o",
  "clone",
  "close",
  "cloud",
  "cloud-download",
  "cloud-upload",
  "code",
  "code-fork",
  "coffee",
  "cog",
  "cogs",
  "comment",
  "comment-o",
  "commenting",
  "commenting-o",
  "comments",
  "comments-o",
  "compass",
  "copyright",
  "creative-commons",
  "credit-card",
  "credit-card-alt",
  "crop",
  "crosshairs",
  "cube",
  "cubes",
  "cutlery",
  "dashboard",
  "database",
  "desktop",
  "diamond",
  "dot-circle-o",
  "download",
  "edit",
  "ellipsis-h",
  "ellipsis-v",
  "envelope",
  "envelope-o",
  "envelope-square",
  "eraser",
  "exchange",
  "exclamation",
  "exclamation-circle",
  "exclamation-triangle",
  "external-link",
  "external-link-square",
  "eye",
  "eye-slash",
  "eyedropper",
  "fax",
  "feed",
  "female",
  "fighter-jet",
  "file-archive-o",
  "file-audio-o",
  "file-code-o",
  "file-excel-o",
  "file-image-o",
  "file-movie-o",
  "file-pdf-o",
  "file-photo-o",
  "file-picture-o",
  "file-powerpoint-o",
  "file-sound-o",
  "file-video-o",
  "file-word-o",
  "file-zip-o",
  "film",
  "filter",
  "fire",
  "fire-extinguisher",
  "flag",
  "flag-checkered",
  "flag-o",
  "flash",
  "flask",
  "folder",
  "folder-o",
  "folder-open",
  "folder-open-o",
  "frown-o",
  "futbol-o",
  "gamepad",
  "gavel",
  "gear",
  "gears",
  "gift",
  "glass",
  "globe",
  "graduation-cap",
  "group",
  "hand-grab-o",
  "hand-lizard-o",
  "hand-paper-o",
  "hand-peace-o",
  "hand-pointer-o",
  "hand-rock-o",
  "hand-scissors-o",
  "hand-spock-o",
  "hand-stop-o",
  "hashtag",
  "hdd-o",
  "headphones",
  "heart",
  "heart-o",
  "heartbeat",
  "history",
  "home",
  "hotel",
  "hourglass",
  "hourglass-1",
  "hourglass-2",
  "hourglass-3",
  "hourglass-end",
  "hourglass-half",
  "hourglass-o",
  "hourglass-start",
  "i-cursor",
  "image",
  "inbox",
  "industry",
  "info",
  "info-circle",
  "institution",
  "key",
  "keyboard-o",
  "language",
  "laptop",
  "leaf",
  "legal",
  "lemon-o",
  "level-down",
  "level-up",
  "life-bouy",
  "life-buoy",
  "life-ring",
  "life-saver",
  "lightbulb-o",
  "line-chart",
  "location-arrow",
  "lock",
  "magic",
  "magnet",
  "mail-forward",
  "mail-reply",
  "mail-reply-all",
  "male",
  "map",
  "map-marker",
  "map-o",
  "map-pin",
  "map-signs",
  "meh-o",
  "microphone",
  "microphone-slash",
  "minus",
  "minus-circle",
  "minus-square",
  "minus-square-o",
  "mobile",
  "mobile-phone",
  "money",
  "moon-o",
  "mortar-board",
  "motorcycle",
  "mouse-pointer",
  "music",
  "navicon",
  "newspaper-o",
  "object-group",
  "object-ungroup",
  "paint-brush",
  "paper-plane",
  "paper-plane-o",
  "paw",
  "pencil",
  "pencil-square",
  "pencil-square-o",
  "percent",
  "phone",
  "phone-square",
  "photo",
  "picture-o",
  "pie-chart",
  "plane",
  "plug",
  "plus",
  "plus-circle",
  "plus-square",
  "plus-square-o",
  "power-off",
  "print",
  "puzzle-piece",
  "qrcode",
  "question",
  "question-circle",
  "quote-left",
  "quote-right",
  "random",
  "recycle",
  "refresh",
  "registered",
  "remove",
  "reorder",
  "reply",
  "reply-all",
  "retweet",
  "road",
  "rocket",
  "rss",
  "rss-square",
  "search",
  "search-minus",
  "search-plus",
  "send",
  "send-o",
  "server",
  "share",
  "share-alt",
  "share-alt-square",
  "share-square",
  "share-square-o",
  "shield",
  "ship",
  "shopping-bag",
  "shopping-basket",
  "shopping-cart",
  "sign-in",
  "sign-out",
  "signal",
  "sitemap",
  "sliders",
  "smile-o",
  "soccer-ball-o",
  "sort",
  "sort-alpha-asc",
  "sort-alpha-desc",
  "sort-amount-asc",
  "sort-amount-desc",
  "sort-asc",
  "sort-desc",
  "sort-down",
  "sort-numeric-asc",
  "sort-numeric-desc",
  "sort-up",
  "space-shuttle",
  "spinner",
  "spoon",
  "square",
  "square-o",
  "star",
  "star-half",
  "star-half-empty",
  "star-half-full",
  "star-half-o",
  "star-o",
  "sticky-note",
  "sticky-note-o",
  "street-view",
  "suitcase",
  "sun-o",
  "support",
  "tablet",
  "tachometer",
  "tag",
  "tags",
  "tasks",
  "taxi",
  "television",
  "terminal",
  "thumb-tack",
  "thumbs-down",
  "thumbs-o-down",
  "thumbs-o-up",
  "thumbs-up",
  "ticket",
  "times",
  "times-circle",
  "times-circle-o",
  "tint",
  "toggle-down",
  "toggle-left",
  "toggle-off",
  "toggle-on",
  "toggle-right",
  "toggle-up",
  "trademark",
  "trash",
  "trash-o",
  "tree",
  "trophy",
  "truck",
  "tty",
  "tv",
  "umbrella",
  "university",
  "unlock",
  "unlock-alt",
  "unsorted",
  "upload",
  "user",
  "user-plus",
  "user-secret",
  "user-times",
  "users",
  "video-camera",
  "volume-down",
  "volume-off",
  "volume-up",
  "warning",
  "wheelchair",
  "wifi",
  "wrench",
];

export const animationNames = [
  "",
  "bounce",
  "flash",
  "pulse",
  "rotate",
  "rubberBand",
  "shake",
  "swing",
  "tada",
  "wobble",
  "bounceIn",
  "bounceInDown",
  "bounceInLeft",
  "bounceInRight",
  "bounceInUp",
  "fadeIn",
  "fadeInDown",
  "fadeInDownBig",
  "fadeInLeft",
  "fadeInLeftBig",
  "fadeInRight",
  "fadeInRightBig",
  "fadeInUp",
  "fadeInUpBig",
  "flipInX",
  "flipInY",
  "lightSpeedIn",
  "slideInDown",
  "slideInLeft",
  "slideInRight",
  "slideInUp",
  "zoomIn",
  "zoomInDown",
  "zoomInLeft",
  "zoomInRight",
  "zoomInUp",
];

export const Users = [
  {
    id: 1,
    name: "John Doe",
    email: "G4i8o@example.com",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.",
    image:
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    address: "123 Main St, City, Country",
    phone: "+1-234-567-8900",
    gender: "male",
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "jane@example",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.",
    image:
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    address: "123 Main St, City, Country",
    phone: "+1-234-567-8900",
    gender: "female",
  },
  {
    id: 3,
    name: "Ajay Jang",
    email: "G4i8o@example.com",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.",
    image:
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    address: "123 Main St, City, Country",
    phone: "+1-234-567-8900",
    gender: "male",
  },
  {
    id: 4,
    name: "Kristen Ken",
    email: "jane@example",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.",
    image:
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    address: "123 Main St, City, Country",
    phone: "+1-234-567-8900",
    gender: "female",
  },
  {
    id: 5,
    name: "Gowtham",
    email: "G4i8o@example.com",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.",
    image:
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    address: "123 Main St, City, Country",
    phone: "+1-234-567-8900",
    gender: "male",
  },
  {
    id: 6,
    name: "Jenny",
    email: "jane@example",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.",
    image:
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    address: "123 Main St, City, Country",
    phone: "+1-234-567-8900",
    gender: "female",
  },
  {
    id: 7,
    name: "Aman",
    email: "G4i8o@example.com",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.",
    image:
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    address: "123 Main St, City, Country",
    phone: "+1-234-567-8900",
    gender: "male",
  },
  {
    id: 8,
    name: "Priyanka",
    email: "jane@example",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.",
    image:
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    address: "123 Main St, City, Country",
    phone: "+1-234-567-8900",
    gender: "female",
  },
];

export const salesData = [
  {
    Month: "Jan",
    Sales: 65,
    Profit: 28,
    Revenue: 45,
  },
  {
    Month: "Feb",
    Sales: 59,
    Profit: 48,
    Revenue: 52,
  },
  {
    Month: "Mar",
    Sales: 80,
    Profit: 40,
    Revenue: 65,
  },
  {
    Month: "Apr",
    Sales: 81,
    Profit: 19,
    Revenue: 48,
  },
  {
    Month: "May",
    Sales: 56,
    Profit: 86,
    Revenue: 75,
  },
];

export const quarterResults = [
  {
    Quarter: "Q1",
    Revenue: 1200,
    Profit: 400,
    Growth: 15,
  },
  {
    Quarter: "Q2",
    Revenue: 1000,
    Profit: 600,
    Growth: 25,
  },
  {
    Quarter: "Q3",
    Revenue: 1800,
    Profit: 750,
    Growth: 30,
  },
  {
    Quarter: "Q4",
    Revenue: 200,
    Profit: 900,
    Growth: 35,
  },
];

export const carouselImages = [
  {
    image: "https://picsum.photos/800/400?random=3",
    title: "Image 1",
  },
  {
    image: "https://picsum.photos/800/400?random=332",
    title: "Image 2",
  },
  {
    image: "https://picsum.photos/800/400?random=32",
    title: "Image 3",
  },
  {
    image: "https://picsum.photos/800/400?random=36",
    title: "Image 4",
  },
  {
    image: "https://picsum.photos/800/400?random=37",
    title: "Image 5",
  },
];
